package uz.qrscanner.qrcodescanner.barcodereader.barcodescanner.designsystem.resources

import uz.qrscanner.qrcodescanner.barcodereader.barcodescanner.data.model.GenerateType

object AppStrings {
    const val appName = "QR"
    const val loading = "Loading..."
    const val onBoardingDescription =
        "Go and enjoy our features for free and make your life easy with us."
    const val letsStart = "Let's Start"
    const val generateQrCode = "Generate QR Code"
    const val generate = "Generate"
    const val generate_qr = "Generate QR"
    const val history = "History"
    const val result = "Result"
    const val settings = "Settings"
    const val support = "Support"
    const val rateUs = "Rate Us"
    const val rateUsDescription = "Your best reward to us."
    const val share = "Share"
    const val copy = "Copy"
    const val save = "Save"
    const val shareDescription = "Share app with others."
    const val vibrate = "Vibrate"
    const val vibrateDescription = "Vibration when scan is done."
    const val beep = "Beep"
    const val beepDescription = "Beep when scan is done."
    const val text = "Text"
    const val website = "Website"
    const val websiteUrl = "Website URL"
    const val wifi = "Wi-Fi"
    const val event = "Event"
    const val contact = "Contact"
    const val business = "Business"
    const val location = "Location"
    const val phone = "Phone"
    const val sms = "SMS"
    const val email = "Email"
    const val youtube = "YouTube"
    const val whatsApp = "WhatsApp"
    const val instagram = "Instagram"
    const val facebook = "Facebook"
    const val twitter = "Twitter"
    const val tiktok = "TikTok "
    const val telegram = "Telegram"
    const val twitch = "Twitch"
    const val linkedin = "LinkedIn"
    const val github = "Github"
    const val enterText = "Enter text"
    const val enterEmailAddress = "Enter email address"
    const val enterPhoneNumber = "Enter phone number"
    const val enterPassword = "Enter password"
    const val enterNetworkName = "Enter network name"
    const val enterName = "Enter name"
    const val enterMessage = "Enter message"
    const val enterWebsite = "Enter website"
    const val enterAddress = "Enter address"
    const val enterValue = "Enter value"
    const val enterLocation = "Enter location"
    const val enterAnyDetails = "Enter any details"
    const val firstName = "First name"
    const val middleName = "Last name"
    const val lastName = "Last name"
    const val password = "Password"
    const val username = "Username"
    const val phoneNumber = "Phone number"
    const val network = "Network"
    const val ok = "OK"
    const val message = "Message"
    const val copied = "Copied"
    const val driverLicense = "Driver license"
    const val address = "Address"
    const val companyName = "Company name"
    const val industry = "Industry"
    const val egIndustry = "e.g Food/Agency"
    const val egGoogle = "e.g google.com"
    const val documentType = "Document type"
    const val gender = "Gender"
    const val addressStreet = "Address street"
    const val addressCity = "Address city"
    const val addressZip = "Address zip"
    const val licenseNumber = "License number"
    const val issueDate = "Issue date"
    const val expiryDate = "Expiry date"
    const val birthDate = "Birth date"
    const val issuingCountry = "Issuing country"
    const val latitude = "Latitude"
    const val longitude = "Longitude"
    const val selectLocation = "Select location"
    const val actionSelect = "Select"
    const val eventName = "Event Name"
    const val eventLocation = "Event Location"
    const val description = "Description"
    const val startDateAndTime = "Start Date and Time"
    const val endDateAndTime = "End Date and Time"
    const val egDateAndTime = "e.g 12 Dec 2023, 10:40"
    const val cancel = "Cancel"
    const val selectTime = "Select time"
    const val selectDate = "Select date"

    fun enterUsername(type: GenerateType): String {
        return "Enter ${type.title} username"
    }
}