package uz.qrscanner.qrcodescanner.barcodereader.barcodescanner.designsystem.resources

import uz.qrscanner.qrcodescanner.barcodereader.barcodescanner.data.model.GenerateType

internal object AppStrings {
    const val appName = "QR"
    const val loading = "Loading..."
    const val onBoardingDescription = "Go and enjoy our features for free and make your life easy with us."
    const val actionLetsStart = "Let's Start"
    const val actionGenerateQrCode = "Generate QR Code"
    const val generate = "Generate"
    const val generate_qr = "Generate QR"
    const val history = "History"
    const val settings = "Settings"
    const val support = "Support"
    const val rateUs = "Rate Us"
    const val rateUsDescription = "Your best reward to us."
    const val share = "Share"
    const val shareDescription = "Share app with others."
    const val vibrate = "Vibrate"
    const val vibrateDescription = "Vibration when scan is done."
    const val beep = "Beep"
    const val beepDescription = "Beep when scan is done."
    const val text = "Text"
    const val website = "Website"
    const val websiteUrl = "Website URL"
    const val wifi = "Wi-Fi"
    const val event = "Event"
    const val contact = "Contact"
    const val business = "Business"
    const val location = "Location"
    const val telephone = "Telephone"
    const val email = "Email"
    const val youtube = "YouTube"
    const val whatsApp = "WhatsApp"
    const val instagram = "Instagram"
    const val facebook = "Facebook"
    const val twitter = "Twitter"
    const val tiktok = "TikTok "
    const val telegram = "Telegram"
    const val twitch = "Twitch"
    const val linkedin = "LinkedIn"
    const val github = "Github"
    const val enterText = "Enter text"
    const val enterEmailAddress = "Enter email address"
    const val googleCom = "google.com"
    const val username = "Username"

    fun enterUsername(type: GenerateType): String {
        return "Enter ${type.title} username"
    }
}